version: '3.8'

services:
  gradle-runner:
    image: eclipse-temurin:21-jdk
    volumes:
      - .:/workspace
    working_dir: /workspace
    env_file:
      - .env.test
    environment:
      GRADLE_USER_HOME: /workspace/var/gradle
      HOME: /workspace/var/gradle
      DATABASE_JDBCURL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-unicoach-test}
    # Command overridden by `bin/test`
    command: ./gradlew test

networks:
  default:
    external: true
    name: unicoach-network
