rootProject.name = "unicoach"
include("common")
include("service")
include("rest-server")
include("db")
include("queue")
include("queue-worker")
include("net")
include("email")
include("chat")
include("admin-server")
include("public-web")
