rootProject.name = "unicoach"
include("common")
include("web-common")
include("service")
include("rest-server")
include("db")
include("queue")
include("queue-worker")
include("cron")
include("net")
include("auth")
include("email")
include("chat")
include("appstore")
include("admin-web")
include("public-web")
include("college")
