server {
    port = 8080
    port = ${?SERVER_PORT}
    host = "0.0.0.0"
    host = ${?SERVER_HOST}
}

session {
    cookieName = "UNICOACH_SESSION"
    cookieName = ${?SESSION_COOKIE_NAME}
    cookieDomain = "localhost"
    cookieDomain = ${?SESSION_COOKIE_DOMAIN}
    cookieSecure = false
    cookieSecure = ${?SESSION_COOKIE_SECURE}
    expiration = "7d"
    expiration = ${?SESSION_EXPIRATION}
}

sessionExpiry {
    ignorePathPrefixes = ["/health"]
}
