ktor {
    deployment {
        port = ${PORT}
        host = "0.0.0.0"
    }
    application {
        modules = [ ed.unicoach.rest.ApplicationKt.module ]
    }
}

jwt {
    secret = ${JWT_SECRET}
    issuer = ${JWT_ISSUER}
}

include "service.conf"
