-- Published codebook reference tables. RFC 147 (brief 0004 substrate slice).
--
-- The eleven tables below hold the PUBLISHED meaning of the federal codes the
-- repo already stores raw (`colleges.region`, `colleges.locale`,
-- `college_ipeds.carnegie_basic`, ...). Every row is generated by
-- `bin/fetch-codebooks` from the IPEDS Stata `.do` syntax files committed under
-- `db/seed/codebooks/`, emitted into `db/data/codebooks.json`, and loaded by the
-- `codebooks` phase of `bin/ingest-colleges` (CodebookLoader). Nothing here is
-- authored by hand: a wrong label is fixed by regenerating the file, where the
-- diff is reviewable, never by an UPDATE.
--
-- Reference tables in the 0015/0054/0055 sense: unversioned, no soft delete, no
-- OCC, upserted on their natural key by re-ingestion and never touched by
-- request flow. They carry the house created_at/updated_at pair with the plain
-- `update_colleges_timestamp()` trigger from 0000/0015 (touches only
-- updated_at), so an unchanged re-load leaves each row byte-identical.
--
-- NOT foreign keys (D46). `colleges.region`, `colleges.locale` and the
-- `college_ipeds` code columns keep their existing range CHECKs; tightening one
-- into a real FK is a constraint change on a live source table and belongs with
-- the ingest that fills it (RFC 148). Until then the loader REPORTS every stored
-- code with no codebook row, per column, with counts. The one FK here is
-- internal: `us_states.ipeds_region` -> `ipeds_regions(slug)`, published data
-- referring to published data.
--
-- Vintage is in the NAME, not in a key (D42): `C21BASIC` already names its
-- 2021 classification, so the table is `carnegie_2021_basic_classes` and the
-- slug is the whole primary key. `codebook_sources` records each domain's
-- survey vintage, artifact and digest; keying every reference row by survey year
-- would push a join onto every read of a vocabulary that changes every few
-- years.
--
-- No physical indexes beyond the PRIMARY KEY / UNIQUE constraints: the largest
-- table is `cip_codes` at 1,710 rows and every read is by key.

-- ---------------------------------------------------------------------------
-- The shared `slug` domain (D44).
--
-- Nine tables key on a slug, so the pattern is declared ONCE rather than copied
-- as nine identical per-column CHECKs — the same de-duplication argument
-- `cds_factor_rating` (0054) makes: a bound written nine times is an edit that
-- can be missed in one of them. The slugs themselves are produced by one
-- slugify rule plus an explicit override map inside `bin/fetch-codebooks`, so
-- regeneration is reproducible.
--
-- `usd` and `share` domains are deliberately NOT introduced here (D44): they
-- belong with the columns that need them, and retyping existing `colleges`
-- columns is a table rewrite this slice has no reason to run.
-- ---------------------------------------------------------------------------

CREATE DOMAIN slug AS TEXT
    CONSTRAINT slug_check
    CHECK (VALUE ~ '^[a-z0-9]+(-[a-z0-9]+)*$');

-- ---------------------------------------------------------------------------
-- ipeds_regions — HD2023 OBEREG. The region code `colleges.region` stores.
--
-- `label_raw` is the published string VERBATIM, including the state list the
-- label crams onto the end ("New England CT ME MA NH RI VT"); `name` is the
-- generator's repaired, human half ("New England") and the membership lands as
-- `us_states.ipeds_region` (D38/D39). Both are kept: the raw string is the
-- evidence, the parsed columns are what anything reads.
-- ---------------------------------------------------------------------------

CREATE TABLE ipeds_regions (
    slug       slug        NOT NULL PRIMARY KEY,
    code       SMALLINT    NOT NULL UNIQUE,          -- HD.OBEREG (0 = U.S. Service schools)
    name       TEXT        NOT NULL,                 -- parsed, caret-repaired
    label_raw  TEXT        NOT NULL,                 -- the published label, byte for byte
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trigger_03_enforce_ipeds_regions_updated_at
BEFORE UPDATE ON ipeds_regions
FOR EACH ROW
EXECUTE PROCEDURE update_colleges_timestamp();

-- ---------------------------------------------------------------------------
-- us_states — HD2023 STABBR names, keyed by the postal code `colleges.state`
-- stores, plus the OBEREG membership parsed out of the region labels.
--
-- All 59 rows are published: HD2023 names exactly the 59 OBEREG members, so no
-- state-name table was authored (the generator fatal-checks the mapping in both
-- directions and asserts exactly 50 states). `jurisdiction_kind` is the ONE
-- authored column in this migration's data — DC is a federal district, AS/GU/
-- MP/PR/VI are territories, and FM/MH/PW are freely-associated states (COFA
-- countries, NOT U.S. territories) — because IPEDS publishes no such column and
-- a UI that says "state" about Palau is wrong.
-- ---------------------------------------------------------------------------

CREATE TABLE us_states (
    usps_code         TEXT        NOT NULL PRIMARY KEY,
    name              TEXT        NOT NULL UNIQUE,   -- HD.STABBR value label
    jurisdiction_kind TEXT        NOT NULL,          -- authored (see header)
    ipeds_region      slug        NOT NULL REFERENCES ipeds_regions(slug),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT us_states_usps_code_format_check CHECK (usps_code ~ '^[A-Z]{2}$'),
    CONSTRAINT us_states_jurisdiction_kind_check
        CHECK (jurisdiction_kind IN ('state', 'federal-district', 'territory',
                                     'freely-associated-state'))
);

COMMENT ON COLUMN us_states.jurisdiction_kind IS
    'Authored, not published: IPEDS ships no such column. FM/MH/PW are freely '
    'associated states (COFA countries), not U.S. territories.';

CREATE TRIGGER trigger_03_enforce_us_states_updated_at
BEFORE UPDATE ON us_states
FOR EACH ROW
EXECUTE PROCEDURE update_colleges_timestamp();

-- ---------------------------------------------------------------------------
-- nces_locales — HD2023 LOCALE, the NCES urban-centric locale `colleges.locale`
-- stores. The published label is "Type: Detail" ("Rural: Fringe"), and D39
-- stores that structure as columns: `type` + `detail` is what makes "a small
-- town college" a sourced filter rather than a guess.
--
-- There is deliberately NO `definition_raw` column. RFC 147's D37 reserved one
-- for the publisher's own prose definition (NCES Exhibit A), but Exhibit A is a
-- separate WEB document and is not a member of HD2023_Stata.zip, so the
-- generator has nothing to put in it and every row would be NULL. A column that
-- advertises a fact the data never carries is the kind of claim this slice
-- exists to delete; when a publisher ships a definition beside the labels, the
-- column arrives with the data that fills it.
-- ---------------------------------------------------------------------------

CREATE TABLE nces_locales (
    slug           slug        NOT NULL PRIMARY KEY,
    code           SMALLINT    NOT NULL UNIQUE,      -- HD.LOCALE (11..43)
    type           TEXT        NOT NULL,             -- parsed left of the colon
    detail         TEXT        NOT NULL,             -- parsed right of the colon
    name           TEXT        NOT NULL,
    label_raw      TEXT        NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT nces_locales_type_check CHECK (type IN ('city', 'suburb', 'town', 'rural')),
    CONSTRAINT nces_locales_detail_check
        CHECK (detail IN ('large', 'midsize', 'small', 'fringe', 'distant', 'remote'))
);

CREATE TRIGGER trigger_03_enforce_nces_locales_updated_at
BEFORE UPDATE ON nces_locales
FOR EACH ROW
EXECUTE PROCEDURE update_colleges_timestamp();

-- ---------------------------------------------------------------------------
-- carnegie_2021_basic_classes — HD2023 C21BASIC. `degree_level` and `qualifier`
-- are the parsed halves of "Doctoral Universities: Very High Research
-- Activity"; both are NULLABLE because the published set includes rows with no
-- such structure (the `-2` "not in the Carnegie universe" row, which 0055
-- preserves as a real "explicitly none" rather than a sentinel — D41).
-- ---------------------------------------------------------------------------

CREATE TABLE carnegie_2021_basic_classes (
    slug         slug        NOT NULL PRIMARY KEY,
    code         SMALLINT    NOT NULL UNIQUE,        -- HD.C21BASIC (-2 = not classified)
    degree_level TEXT        NULL,                   -- parsed left of the colon
    qualifier    TEXT        NULL,                   -- parsed right of the colon
    name         TEXT        NOT NULL,
    label_raw    TEXT        NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trigger_03_enforce_carnegie_2021_basic_classes_updated_at
BEFORE UPDATE ON carnegie_2021_basic_classes
FOR EACH ROW
EXECUTE PROCEDURE update_colleges_timestamp();

-- ---------------------------------------------------------------------------
-- carnegie_2021_size_settings — HD2023 C21SZSET, parsed into the three things
-- the label actually says ("Four-year, small, highly residential"): how many
-- years, what size, and what residential character. This is the row that makes
-- "small residential college" answerable from published data instead of from a
-- guessed enrollment threshold (D39).
--
-- All three parsed columns are NULLABLE: two published codes carry no such
-- structure (18 "not classified" and the -2 row).
-- ---------------------------------------------------------------------------

CREATE TABLE carnegie_2021_size_settings (
    slug                  slug        NOT NULL PRIMARY KEY,
    code                  SMALLINT    NOT NULL UNIQUE,   -- HD.C21SZSET (-2 = not classified)
    years                 SMALLINT    NULL,              -- 2 or 4, parsed from "Two/Four-year"
    -- Left unconstrained and UNTRANSCRIBED on purpose: the published vocabulary
    -- is whatever C21SZSET's labels carry, and a hand-written list here would be
    -- one more codebook nobody regenerates (this comment used to name four
    -- values where the data ships five). Read carnegie_2021_size_settings.
    size                  TEXT        NULL,              -- parsed from the label's size clause
    residential_character TEXT        NULL,              -- e.g. "highly residential"
    name                  TEXT        NOT NULL,
    label_raw             TEXT        NOT NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT carnegie_2021_size_settings_years_check CHECK (years IS NULL OR years IN (2, 4))
);

CREATE TRIGGER trigger_03_enforce_carnegie_2021_size_settings_updated_at
BEFORE UPDATE ON carnegie_2021_size_settings
FOR EACH ROW
EXECUTE PROCEDURE update_colleges_timestamp();

-- ---------------------------------------------------------------------------
-- religious_affiliations — IC2023 RELAFFIL, the code `college_ipeds.rel_affil`
-- stores. Kept deliberately FLAT (D39): beyond the denomination name the
-- published labels carry no reliable structure, and inventing a grouping here
-- would be our taxonomy wearing the publisher's clothes.
-- ---------------------------------------------------------------------------

CREATE TABLE religious_affiliations (
    slug       slug        NOT NULL PRIMARY KEY,
    code       SMALLINT    NOT NULL UNIQUE,           -- IC.RELAFFIL (-2 = explicitly none)
    name       TEXT        NOT NULL,
    label_raw  TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trigger_03_enforce_religious_affiliations_updated_at
BEFORE UPDATE ON religious_affiliations
FOR EACH ROW
EXECUTE PROCEDURE update_colleges_timestamp();

-- ---------------------------------------------------------------------------
-- athletic_associations — IC2023 ASSOC1..6 VARIABLE labels (D40). ASSOC1..6 is
-- not a code list: it is six yes/no flags whose meaning lives in the variable
-- label ("Member of National Collegiate Athletic Association (NCAA)"), so the
-- generator emits the variable labels as rows.
--
-- `code` is the ASSOC ORDINAL (1..6) — exactly what `college_ipeds.athletic_assoc`
-- stores as a smallint[] (RFC 144). The RFC's schema block listed only
-- `source_variable`; the ordinal is carried as a first-class column because it
-- is the stored value, and D46's unknown-code report has to join on it.
-- ---------------------------------------------------------------------------

CREATE TABLE athletic_associations (
    slug            slug        NOT NULL PRIMARY KEY,
    code            SMALLINT    NOT NULL UNIQUE,      -- the ASSOC ordinal college_ipeds stores
    source_variable TEXT        NOT NULL UNIQUE,      -- 'assoc1'..'assoc6'
    name            TEXT        NOT NULL,             -- variable label, whitespace-repaired
    label_raw       TEXT        NOT NULL,             -- verbatim (ASSOC3 has a double space)
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT athletic_associations_code_range_check CHECK (code BETWEEN 1 AND 6),
    CONSTRAINT athletic_associations_source_variable_format_check
        CHECK (source_variable ~ '^assoc[1-6]$')
);

COMMENT ON COLUMN athletic_associations.code IS
    'The ASSOC ordinal (1..6) stored in college_ipeds.athletic_assoc, not a '
    'published value-label code: ASSOC1..6 are six flags, one variable each.';

CREATE TRIGGER trigger_03_enforce_athletic_associations_updated_at
BEFORE UPDATE ON athletic_associations
FOR EACH ROW
EXECUTE PROCEDURE update_colleges_timestamp();

-- ---------------------------------------------------------------------------
-- football_conferences — IC2023 CONFNO1, the code `college_ipeds.football_conf`
-- stores.
--
-- CONFNO1..4 do NOT share one value set (the RFC's D40 parenthetical is wrong
-- against the artifact: the four sets hold 100/133/131/130 entries, and codes
-- 202 and 359 carry DIFFERENT published labels between them). Only CONFNO1 —
-- football — is emitted and stored, which is exactly the variable
-- `college_ipeds.football_conf` holds. The measured set sizes are recorded in
-- db/seed/codebooks/PROVENANCE.json so the divergence stays on the record.
-- ---------------------------------------------------------------------------

CREATE TABLE football_conferences (
    slug       slug        NOT NULL PRIMARY KEY,
    code       SMALLINT    NOT NULL UNIQUE,           -- IC.CONFNO1 (-2 = none)
    name       TEXT        NOT NULL,
    label_raw  TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trigger_03_enforce_football_conferences_updated_at
BEFORE UPDATE ON football_conferences
FOR EACH ROW
EXECUTE PROCEDURE update_colleges_timestamp();

-- ---------------------------------------------------------------------------
-- admission_test_policies — ADM2023 ADMCON7, the code `college_ipeds.test_policy`
-- stores: three published codes (1 required, 3 blind, 5 optional). The slugs are
-- the words humans already use — 'required', 'test-blind', 'test-optional'.
-- ---------------------------------------------------------------------------

CREATE TABLE admission_test_policies (
    slug       slug        NOT NULL PRIMARY KEY,
    code       SMALLINT    NOT NULL UNIQUE,           -- ADM.ADMCON7
    name       TEXT        NOT NULL,
    label_raw  TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trigger_03_enforce_admission_test_policies_updated_at
BEFORE UPDATE ON admission_test_policies
FOR EACH ROW
EXECUTE PROCEDURE update_colleges_timestamp();

-- ---------------------------------------------------------------------------
-- cip_codes — C2023_A CIPCODE: 1,710 six-digit codes with their published
-- titles (D43). This closes RFC 144's gap — `college_programs_census` stores
-- codes and no titles — and gives RFC 148's subject taxonomy a validator.
--
-- Keyed by the six-digit code, NOT a slug: the code IS the published key, and
-- 1,710 slugs would add a collision surface for nothing. The two-digit CIP
-- family is `left(code, 2)` and is therefore DERIVED at read time, never stored
-- (CLAUDE.md schema conventions).
--
-- The label set also contains one `99 "Grand total"` AGGREGATE row. It is not a
-- CIP code (no NN.NNNN- prefix, and it cannot satisfy the format CHECK below),
-- so the generator excludes it by name and records the exclusion in
-- PROVENANCE.json — 1,710 codes, not the 1,711 labels.
-- ---------------------------------------------------------------------------

CREATE TABLE cip_codes (
    code       TEXT        NOT NULL PRIMARY KEY,      -- six digits, dot removed
    title      TEXT        NOT NULL,                  -- parsed out of the label
    label_raw  TEXT        NOT NULL,                  -- e.g. '01.0000-Agriculture, General'
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT cip_codes_format_check CHECK (code ~ '^[0-9]{6}$')
);

CREATE TRIGGER trigger_03_enforce_cip_codes_updated_at
BEFORE UPDATE ON cip_codes
FOR EACH ROW
EXECUTE PROCEDURE update_colleges_timestamp();

-- ---------------------------------------------------------------------------
-- codebook_sources — one provenance row per domain, and the reason the drift
-- guard can exist: it records WHICH artifact, at WHICH digest and WHICH survey
-- vintage, the loaded rows came from. Every load compares the stored digest
-- against the one the file declares and reports a change loudly, so a codebook
-- silently regenerated from a different artifact is visible in the run rather
-- than inferred later from a relabelled row.
--
-- `null_sentinels` is the domain's declared absence codes (D41: -1 "not
-- reported" and -3 "not applicable" become NULL at ingest; -2 is real data and
-- is a codebook ROW). The loader asserts no declared sentinel is also a code —
-- the assertion the generator already makes, repeated at the DB boundary
-- because that is where the two halves finally meet.
-- ---------------------------------------------------------------------------

CREATE TABLE codebook_sources (
    domain              TEXT        NOT NULL PRIMARY KEY,   -- the codebooks.json key
    source              TEXT        NOT NULL,               -- e.g. 'IPEDS HD2023 (OBEREG)'
    source_file         TEXT        NOT NULL,               -- e.g. 'HD2023_Stata.zip'
    source_sha256       TEXT        NOT NULL,               -- digest of that artifact
    source_vintage_year SMALLINT    NOT NULL,               -- survey year, e.g. 2023
    null_sentinels      SMALLINT[]  NOT NULL DEFAULT '{}',
    loaded_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT codebook_sources_sha256_format_check CHECK (source_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT codebook_sources_vintage_year_range_check
        CHECK (source_vintage_year BETWEEN 1980 AND 2100)
);

COMMENT ON COLUMN codebook_sources.loaded_at IS
    'When this domain was last loaded. Unlike every other table here, this row '
    'is rewritten on EVERY load (the load time is the fact it records), so its '
    'updated_at advances even when the digest did not change.';

CREATE TRIGGER trigger_03_enforce_codebook_sources_updated_at
BEFORE UPDATE ON codebook_sources
FOR EACH ROW
EXECUTE PROCEDURE update_colleges_timestamp();
