database {
    jdbcUrl = ${?DATABASE_JDBCURL}
    user = ${?DATABASE_USER}
    password = ${?DATABASE_PASSWORD}
    maximumPoolSize = 10
    maximumPoolSize = ${?DATABASE_MAXIMUM_POOL_SIZE}
    connectionTimeout = 30000
}
