database {
    host = "localhost"
    host = ${?DATABASE_HOST}
    jdbcUrl = "jdbc:postgresql://"${database.host}":"${POSTGRES_PORT}"/"${POSTGRES_DB}
    user = ${?DATABASE_USER}
    password = ${?DATABASE_PASSWORD}
    maximumPoolSize = 10
    maximumPoolSize = ${?DATABASE_MAXIMUM_POOL_SIZE}
    connectionTimeout = 30000
}
